# Application
spring.application.name=reppido
server.servlet.context-path=/reppido
spring.mvc.servlet.path=/api/v1

# Server
server.port=8080

# Datasource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Info
info.app.name=${spring.application.name}
info.app.version=@1.0@

logging.level.root=INFO
logging.level.service=DEBUG