# Dev profile

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5433/reppido
spring.datasource.username=postgres
spring.datasource.password=hasjay


# JPA / Hibernate
spring.jpa.show-sql=false

