# Production profile

# Datasource
spring.datasource.url=jdbc:postgresql://reppido-aws.cb6owmeu2o37.ap-southeast-1.rds.amazonaws.com:5432/reppido
spring.datasource.username=postgres
spring.datasource.password=hasjay84


# JPA / Hibernate
spring.jpa.show-sql=false

logging.level.root=INFO
logging.level.service=INFO